apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-prod
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: domain-prod
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60

